from selenium.webdriver.common.by import By


class PersonalDataPageLocators:

    arrow_head_button = (By.XPATH, "//div[@data-dropdown-id='user_dropdown']/button")
    my_account_button = (By.XPATH, '//a[@data-analytics-interaction-value="Konto"]')
    set_name_link = (By.ID, "name-change-btn")
    first_name = (By.ID, "field-7")
    last_name = (By.ID, "field-8")
    cancel_name_link = (By.XPATH, "//button[contains(., 'anuluj')]")
    save_name_button = (By.XPATH, "//button[contains(., 'wyślij wniosek')]")
    set_login_link = (By.ID, "login-change-btn")
    login_input = (By.ID, "field-6")
    cancel_login_link = (By.XPATH, "//button[contains(., 'anuluj')]")
    save_login_button = (By.XPATH, "//button[contains(., 'Zapisz')]")
    set_suposes_name_link = (By.ID, "set-spouse-btn")
    set_supouses_first_name = (By.ID, "field-4")
    set_supouses_last_name = (By.ID, "field-5")
    checkbox_consent = (By.ID, "statement")
    cancel_supouses_link = (By.XPATH, "//button[contains(., 'anuluj')]")
    save_supouses_button = (By.XPATH, "//button[contains(., 'Zapisz')]")
    address_link = (By.XPATH, "//button[contains(.,'Ustaw adres')]")
    street_input = (By.ID, "field-1")
    post_code = (By.ID, "field-2")
    city = (By.ID, "field-3")
    voivodeship_s = (By.ID, "county")
    country_s = (By.ID, "countryCode")
    cancel_address_link = (By.XPATH, "//button[contains(., 'anuluj')]")
    save_address_button = (By.XPATH, "//button[contains(., 'dodaj')]")
    p_name = (By.XPATH, '/html/body/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/div/div[1]/div/div[1]/div[1]/p')
    login_name = (By.XPATH, '/html/body/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/div/div[1]/div/div[2]/div[1]/p')
    supouses_name = (By.XPATH, '/html/body/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/div/div[1]/div/div[2]/div[2]/p')
    address = (By.XPATH, "//div[@data-testid='residential-address-section']/p")